# Generated by Django 3.0.4 on 2020-12-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleImageCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=200)),
                ('time_stamp', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
    ]
